Horizontal: {
  uni_angle: true,
  use_deg: true,
  angle_start_1: -180,
  angle_end_1: 180,
  n_1: 870,
}
Vertical: {
  uni_angle: false,
  use_deg: true,
  angle_start_1: 2,
  angle_end_1: -8.5,
  n_1: 32,
  angle_start_2: -8.5,
  angle_end_2: -24.87,
  n_2: 32
}
